### ISSUE TITLE
mksrc: some values contain trailing new line

### ISSUE THREAD

**Issue by Luashine** [lep/jassdoc#126]
```sql
                    insert into annotations (fnname, anname, value) values (
                        'bj_HASHTABLE_STRING',
                        'source-code',
                        '	constant integer   bj_HASHTABLE_STRING                  = 3
'
                    );
```

These get inserted into the database as `\x0a` (I am on Linux). Even **some** of the `@pure` annotations have that trailing new line while others don't.

Does have new line on pure: OrderId https://github.com/lep/jassdoc/blob/ca10ef7d3a6e359800b2f0605e69f80594b80a9e/common.j#L1376

Does not have: OrderId2String https://github.com/lep/jassdoc/blob/ca10ef7d3a6e359800b2f0605e69f80594b80a9e/common.j#L1395

I see it's simply not trimming trailing new lines from the .j files and processing them literally. That's clutter in my opinion and should be removed.

**Comment by lep** [comment]
Yes, i was aware but i never really wanted to touch newline stuff. But it was easy enough i guess. 972ae3f59a54b9ed6f7d589fc32e00738ef85f46
