### ISSUE TITLE
GetUnitAbilityLevel skills treated as equals

### ISSUE THREAD

**Issue by Tasyen** [lep/jassdoc#152]
GetUnitAbilityLevel treats some abilities as the same. Recently I wanted to check which worker ability an worker has so I did GetUnitAbilityLevel > 0 . But every melee worker had all built skills and returned 1 for any of them.

```Lua
print(GetUnitName(udg_Unit))
local skills = {'ANbu','AHbu','AEbu','AObu','AUbu','AGbu'}
for i, skill in ipairs(skills) do
   print(skill, GetUnitAbilityLevel(udg_Unit, FourCC(skill)))
end
```
![image](https://github.com/lep/jassdoc/assets/50703426/6a9863fe-e405-4162-b4a7-ac7650357850)

**Comment by Luashine** [comment]
Oh, one one hand general stuff about the game should belong to a mapper's wiki, on the other hand we don't have such a wiki and even if we did, would anyone like to look up info in two places?

I will expand the test code and make it a PR. Thanks!

**Comment by Luashine** [comment]
![builders2](https://github.com/lep/jassdoc/assets/103937213/07e4c4d2-ebd2-4747-ab0e-a846629597d5)

nbee is some campaign High Elf "engineer" in name only. He has no building ability. ogru is Grunt for control. I am not sure who all these building skills belong to, I just ran with your list :)

**Comment by lep** [comment]
```
local unit u = CreateUnit(Player(0), 'hpea', 0, 0, 0)
call BJDebugMsg(I2S(GetHandleId(BlzGetUnitAbility(u, 'AHbu'))))
call BJDebugMsg(I2S(GetHandleId(BlzGetUnitAbility(u, 'AObu'))))
```

Yeah, you even get the same ability object (the above should print the same number twice).

**Comment by WaterKnight** [comment]
Also works with `UnitRemoveAbility` and `BlzUnitDisableAbility`.
