### ISSUE TITLE
GetPlayerTechResearched - what are the params

### ISSUE THREAD

**Issue by Cokemonkey11** [lep/jassdoc#21]
https://github.com/lep/jassdoc/blob/98fc2bf27c832d66ec34b0c94915aa3bb0f604a6/player.j#L83

`techid`: is this the `'hfoo'` id of the research/upgrade?
`boolean specificonly` -- ??? wtf

**Comment by WaterKnight** [comment]
https://github.com/lep/jassdoc/compare/master...WaterKnight:jassdoc:patch-5

**Comment by lep** [comment]
Thanks @WaterKnight. I took the liberty to merge your patch.
