### ISSUE TITLE
UnitDamageTarget - does nothing if source is null

### ISSUE THREAD

**Issue by Cokemonkey11** [lep/jassdoc#22]
https://github.com/lep/jassdoc/blob/e568f1c87c3bae564769e60c8477ce2b9a0c3a24/unit.j#L645

the source (first arg) must be an actual unit

Setting source and target as the same unit is an easy way to resolve if intentionally don't have a source

**Comment by lep** [comment]
Closed by 30877e88b203c5932f6b9eef5126c96be9cf62e1
