### ISSUE TITLE
Explanation for current doc annotations

### ISSUE THREAD

**Issue by Luashine** [lep/jassdoc#44]
> So far I have used @param, @bug, @note, @pure, @async and @event annotations. Other possible annotations could be @nosideeffect.

1. Yet [only those have custom representation](https://github.com/lep/jassdoc-browser/blob/master/server.hs#L41-L72)? `async, pure, event`. Everything else appears as normal text, right?
2. I noticed it's markdown, what engine's used? It's not like I'm going to try and insert images, but it's good to know what exactly is supported.
3. What exactly does \@pure mean? [Haskell's definition of pure](https://wiki.haskell.org/Pure)? ie. idempotence?
4. \@patch seems to be used to note when the function has been introduced?
5. \@bug annotations can have a version either in plaintext or as a parsed value. @lep  Your idea of "developers using the sqlite db" to hunt for bugs probably isn't going to become a reality, then for a style guide it would suffice for people to add the affected versions however they like as text: `@bug Reforged:` or `@bug 1.31-1.32.2:` - without adding complexility like `@bug <version> <text>`
    - Versions are important because the community split in 1.26 / to a lesser extent 1.27+ / and official bnet Reforged. One map author told me in a private discussion that a map "doesnt work on Reforged" and his only reason was the Preload differences, which aren't actually compatibility blockers if done right.

I would like to prepare an easy to follow style guide and installation instructions for those willing to contribute. Github is a one hoop on the way to contribution, no need to add more :)

For now I've used the hive's thread to motivate people, so I'm gonna continue discussing technical stuff here.

*Msg updated*

**Comment by lep** [comment]
> 1. Yet [only those have custom representation](https://github.com/lep/jassdoc-browser/blob/master/server.hs#L41-L72)? async, pure, event. Everything else appears as normal text, right?

Yes, but we can always add custom text to any tag.

> 2. I noticed it's markdown, what engine's used? It's not like I'm going to try and insert images, but it's good to know what exactly is supported.

I'm currently using [python markdown](https://python-markdown.github.io/) but i've cycled through some other engines before. The only thing that made problems (so far) are tables.

> 3. What exactly does @pure mean? [Haskell's definition of pure](https://wiki.haskell.org/Pure)? ie. idempotence?

Yes my mental model is that of haskell/mathematical functions. Idempotency can be orthogonal.

> 4. @patch seems to be used to note when the function has been introduced?

Exactly!

> 5. [...] "versioned bugs"

Very good idea! I would have to think about the details. A version string parser could be viable to have some comfort.

> I would like to prepare an easy to follow style guide and installation instructions for those willing to contribute. Github is a one hoop on the way to contribution, no need to add more :)

That would be very nice. I know this tech-stack might be a bit hard to build yourself. I have a personal builder under `/app/ci` but maybe something like github actions could be viable. But i have no experience personally with that.
