### ISSUE TITLE
common.ai documentation?

### ISSUE THREAD

**Issue by Luashine** [lep/jassdoc#71]
With moyack's permission I wanted to move the few [previous contributions remaining on his website](https://wc3modding.info/jassdoc/475/) to here. There's one minor problem: Starquizer dedicated most of his work to the AI natives. These aren't tracked by this jassdoc.

Would you add it? Attached version 1.33.0.19203 (changed file extension due to github restrictions)
[common.ai.txt](https://github.com/lep/jassdoc/files/9649469/common.ai.txt)

**Comment by lep** [comment]
Hell yeah I won't say no to gratis documentation! I assume we should simply use one `common.ai` file and not split it up like common.j
But I'm open for any kind of suggestion or request for help.

**Comment by Luashine** [comment]
If you say yes, I'll commit it as a single `common.ai.j` file in first commit and then add his docs.

**Comment by lep** [comment]
Let's use `common.ai` I think. There already is a common.ai file in here with all the non-common-ai usable natives. I would simply replace the file and add the old and the new documentation.

**Comment by Luashine** [comment]
Is the `@commonai` tag used/unused, what should I do with it?

**Comment by lep** [comment]
> Is the `@commonai` tag used/unused, what should I do with it?

I'm currently using it to [signify](https://github.com/lep/jassbot-bp/blob/master/jassbot/__init__.py#L163-L164) that a native was defined in common.ai but still is usable if you import into your war3map.j
So I'm open to change that tag if anyone got a better name but for now I would simply just tag the same natives, that is natives which work in a normal map script.
